const Payment = require("../models/payment.model");
const Commission = require("../models/commission.model");
const MortgageApplication = require("../models/mortgage-application.model");
const Procurement = require("../models/procurement.model");
const Service = require("../models/service.model");
const AuditLog = require("../models/audit-log.model");

const pagination = (query = {}) => ({ page: Math.max(Number(query.page) || 1, 1), limit: Math.min(Math.max(Number(query.limit) || 25, 1), 100) });
const dates = (query = {}, field = "createdAt") => { const range = {}; if (query.startDate) range.$gte = new Date(query.startDate); if (query.endDate) { const end = new Date(query.endDate); end.setHours(23, 59, 59, 999); range.$lte = end; } return Object.keys(range).length ? { [field]: range } : {}; };
const list = async (model, filter, query, populate = []) => { const { page, limit } = pagination(query); let finder = model.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit); populate.forEach((item) => { finder = finder.populate(item); }); const [records, total] = await Promise.all([finder.lean(), model.countDocuments(filter)]); return { records, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }; };
const amount = (value) => Number(value || 0);
const financeAudit = { category: { $in: ["Finance", "Payment", "Commission", "Procurement"] } };

exports.getOverview = async (query) => {
  const [serviceRevenue, payments, commissions, mortgages, activity] = await Promise.all([
    Service.aggregate([{ $match: { recordType: "transaction", transactionType: "Revenue", transactionStatus: "Completed", ...dates(query) } }, { $group: { _id: null, total: { $sum: "$amount" } } }]),
    Payment.aggregate([{ $group: { _id: "$status", total: { $sum: "$amount" } } }]), Commission.aggregate([{ $group: { _id: "$status", pool: { $sum: "$commissionPool" } } }]),
    MortgageApplication.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]), AuditLog.find(financeAudit).sort({ createdAt: -1 }).limit(6).lean(),
  ]);
  const payment = Object.fromEntries(payments.map((item) => [item._id, item.total]));
  const pendingCommissions = commissions.filter((item) => ["Pending", "Processing", "Overdue"].includes(item._id)).reduce((sum, item) => sum + amount(item.pool), 0);
  return { summary: { realizedServiceRevenue: amount(serviceRevenue[0]?.total), ownerPaymentsCollected: amount(payment.Paid), pendingOwnerPayments: amount(payment.Pending) + amount(payment.Overdue), paidCommissionObligations: amount(commissions.find((item) => item._id === "Paid")?.pool), pendingCommissionObligations: pendingCommissions, activeMortgageApplications: mortgages.filter((item) => !["Rejected", "Cancelled", "Disbursed"].includes(item._id)).reduce((sum, item) => sum + item.count, 0) }, recentActivity: activity.map((item) => ({ id: String(item._id), action: item.action, category: item.category, description: item.description, createdAt: item.createdAt })) };
};
exports.getCounts = async () => {
  const [payments, commissions, mortgageApplications, procurementBudget, auditLogs] = await Promise.all([Payment.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]), Commission.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]), MortgageApplication.countDocuments({ status: { $in: ["Submitted", "Document Verification", "Credit Assessment", "Approved"] } }), Procurement.countDocuments({ recordType: "budget" }), AuditLog.countDocuments(financeAudit)]);
  const pending = (items) => items.filter((item) => ["Pending", "Processing", "Overdue"].includes(item._id)).reduce((total, item) => total + item.count, 0);
  return { ownerPayments: pending(payments), agencyEarnings: pending(commissions), agentCommissions: pending(commissions), mortgageApplications, procurementBudget, auditLogs };
};
exports.getRevenue = async (query) => { const result = await list(Service, { recordType: "transaction", transactionType: "Revenue", transactionStatus: "Completed", ...dates(query, "transactionDate") }, query); return { revenue: result.records.map((item) => ({ id: item.recordId, source: item.transactionDescription || item.name, amount: amount(item.amount), currency: "NGN", status: item.transactionStatus, date: item.transactionDate || item.createdAt, sourceDomain: "Home Services" })), pagination: result.pagination }; };
exports.getTransactions = async (query) => { const [paymentResult, serviceResult] = await Promise.all([list(Payment, dates(query), query, [{ path: "property", select: "title" }]), list(Service, { recordType: "transaction", ...dates(query, "transactionDate") }, query)]); const transactions = [...paymentResult.records.map((item) => ({ id: String(item._id), type: "Owner payment", amount: amount(item.amount), direction: "inflow", status: item.status, date: item.paidAt || item.createdAt, reference: item.reference, sourceDomain: "Payment", description: item.property?.title || item.paymentPeriod })), ...serviceResult.records.map((item) => ({ id: item.recordId, type: item.transactionType || "Service transaction", amount: amount(item.amount), direction: item.transactionType === "Payout" ? "outflow" : "inflow", status: item.transactionStatus || item.status, date: item.transactionDate || item.createdAt, reference: item.recordId, sourceDomain: "Home Services", description: item.transactionDescription || item.name }))].sort((a, b) => new Date(b.date) - new Date(a.date)); return { transactions, pagination: { ...paymentResult.pagination, total: paymentResult.pagination.total + serviceResult.pagination.total } }; };
exports.getOwnerPayments = async (query) => { const filter = { ...dates(query) }; if (query.status) filter.status = query.status; const result = await list(Payment, filter, query, [{ path: "owner", select: "fullName" }, { path: "property", select: "title" }]); return { payments: result.records.map((item) => ({ id: String(item._id), owner: item.owner?.fullName || "Unknown owner", property: item.property?.title || "Unknown property", amount: amount(item.amount), currency: "NGN", period: item.paymentPeriod, status: item.status, date: item.paidAt || item.createdAt, reference: item.reference })), pagination: result.pagination }; };
const commissionsFor = (kind) => async (query) => { const filter = { ...dates(query) }; if (query.status) filter.status = query.status; const result = await list(Commission, filter, query, [{ path: kind, select: "name fullName" }, { path: "property", select: "title" }]); return { records: result.records.map((item) => ({ id: item.commissionId, recipient: item[kind]?.name || item[kind]?.fullName || "Unknown", property: item.property?.title || "Unknown property", amount: amount(kind === "agency" ? item.agencyAmount : item.agentAmount), currency: "NGN", status: item.status, dueDate: item.dueDate, paidAt: item.paidAt, createdAt: item.createdAt })), pagination: result.pagination }; };
exports.getAgencyEarnings = commissionsFor("agency"); exports.getAgentCommissions = commissionsFor("agent");
exports.getMortgageStatistics = async (query) => { const filter = { ...dates(query) }; if (query.status) filter.status = query.status; const result = await list(MortgageApplication, filter, query, [{ path: "buyer", select: "fullName" }, { path: "property", select: "title" }]); const statuses = await MortgageApplication.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]); return { applications: result.records.map((item) => ({ id: String(item._id), applicant: item.buyer?.fullName || "Unknown buyer", lender: item.lender, property: item.property?.title || "", requestedLoanAmount: amount(item.requestedLoanAmount), approvedLoanAmount: amount(item.approvedLoanAmount), interestRate: item.interestRate, status: item.status, createdAt: item.createdAt })), statusCounts: Object.fromEntries(statuses.map((item) => [item._id, item.count])), pagination: result.pagination }; };
exports.getProcurementBudget = async (query) => { const filter = { recordType: "budget", ...dates(query) }; if (query.status) filter.status = query.status; const result = await list(Procurement, filter, query); return { budgets: result.records.map((item) => ({ id: item.recordId, name: item.name, department: item.department, category: item.category, amount: amount(item.amount), currency: item.currency, status: item.status, dueDate: item.dueDate, createdAt: item.createdAt })), pagination: result.pagination }; };
exports.getReports = async (query) => ({ generatedAt: new Date(), report: { ...(await exports.getOverview(query)).summary, counts: await exports.getCounts(), note: "Only completed Home Services revenue is reported as realized revenue. Listing prices, offers, mortgage approvals, and procurement budgets are excluded." } });
exports.getAuditLogs = async (query) => { const result = await list(AuditLog, { ...financeAudit, ...dates(query) }, query, [{ path: "actor", select: "fullName" }]); return { logs: result.records.map((item) => ({ id: String(item._id), action: item.action, category: item.category, description: item.description, actor: item.actor?.fullName || item.actorName, createdAt: item.createdAt })), pagination: result.pagination }; };
exports.getForecasting = async (query) => { const history = await Service.aggregate([{ $match: { recordType: "transaction", transactionType: "Revenue", transactionStatus: "Completed", transactionDate: { $ne: null }, ...dates(query, "transactionDate") } }, { $group: { _id: { year: { $year: "$transactionDate" }, month: { $month: "$transactionDate" } }, actual: { $sum: "$amount" } } }, { $sort: { "_id.year": 1, "_id.month": 1 } }]); const historical = history.map((item) => ({ period: `${item._id.year}-${String(item._id.month).padStart(2, "0")}`, actual: amount(item.actual) })); if (history.length < 3) return { sufficientData: false, historical, estimates: [] }; const average = historical.reduce((sum, item) => sum + item.actual, 0) / historical.length; return { sufficientData: true, method: "Simple average of completed Home Services revenue months", historical, estimates: [1, 2, 3].map((monthsAhead) => ({ monthsAhead, estimatedRevenue: average })) }; };
