const Property = require("../models/property.model");
const Tenant = require("../models/tenant-occupancy.model");
const Lease = require("../models/lease.model");
const WorkOrder = require("../models/maintenance-work-order.model");
const Inspection = require("../models/inspection.model");
const Expense = require("../models/expense.model");
const Income = require("../models/income.model");
const Payment = require("../models/payment.model");
const Procurement = require("../models/procurement.model");
const AppError = require("../utils/AppError");

const MANAGEMENT_ROLES = ["Property Manager", "Admin", "Super Admin"];
const assertManagerRole = (user) => { if (!user?._id || !user?.role) throw new AppError("Authenticated user information is required", 401); if (!MANAGEMENT_ROLES.includes(user.role)) throw new AppError("You do not have Property Manager access", 403); };
const propertyFilterFor = (user) => { assertManagerRole(user); return user.role === "Property Manager" ? { propertyManager: user._id } : {}; };

// This is the mandatory property-level authorization boundary for every
// management record detail and mutation.
const assertPortfolioAccess = async (propertyId, user) => {
  assertManagerRole(user);
  const property = await Property.findById(propertyId).select("_id propertyManager");
  if (!property) throw new AppError("Property not found", 404);
  if (user.role === "Property Manager" && (!property.propertyManager || String(property.propertyManager) !== String(user._id))) throw new AppError("You can only access properties assigned to you", 403);
  return property;
};
const portfolioPropertyIds = async (user) => (await Property.find(propertyFilterFor(user)).select("_id")).map((property) => property._id);

const listRecords = async (Model, user, query = {}, populate = []) => {
  const ids = await portfolioPropertyIds(user); const filter = { property: { $in: ids } };
  // Do not replace the portfolio constraint with a caller-controlled id.
  // The explicit check keeps a Property Manager from using a list filter to
  // inspect another manager's records.
  if (query.propertyId) { await assertPortfolioAccess(query.propertyId, user); filter.property = query.propertyId; }
  if (query.tenantId) filter.tenant = query.tenantId;
  if (query.status) filter.status = query.status;
  if (query.category) filter.category = query.category;
  const dateField = Model.modelName === "Lease" ? "endDate" : Model.modelName === "Expense" ? "expenseDate" : Model.modelName === "Income" ? "incomeDate" : Model.modelName === "Inspection" ? "scheduledAt" : "createdAt";
  if (query.from || query.to) { filter[dateField] = {}; if (query.from) filter[dateField].$gte = new Date(query.from); if (query.to) filter[dateField].$lte = new Date(query.to); }
  if (query.search && Model.modelName === "TenantOccupancy") filter.$or = [{ fullName: new RegExp(query.search, "i") }, { email: new RegExp(query.search, "i") }, { phone: new RegExp(query.search, "i") }];
  if (query.search && Model.modelName === "MaintenanceWorkOrder") filter.$or = [{ title: new RegExp(query.search, "i") }, { description: new RegExp(query.search, "i") }];
  const page = query.page || 1; const limit = query.limit || 25;
  let request = Model.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit); populate.forEach((value) => { request = request.populate(value); });
  const [records, total] = await Promise.all([request, Model.countDocuments(filter)]); return { records, total, page, limit };
};
const getScopedRecord = async (Model, id, user, populate = []) => { let request = Model.findById(id); populate.forEach((value) => { request = request.populate(value); }); const record = await request; if (!record) throw new AppError("Record not found", 404); await assertPortfolioAccess(record.property, user); return record; };
const getPortfolioProperties = (user) => Property.find(propertyFilterFor(user)).populate("owner", "fullName email phone").populate("propertyManager", "fullName email phone").sort({ createdAt: -1 });

const createTenant = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); return Tenant.create({ property: data.propertyId, tenantUser: data.tenantUserId || null, fullName: data.fullName, email: data.email || null, phone: data.phone || null, unit: data.unit || null, status: data.status, moveInDate: data.moveInDate || null, moveOutDate: data.moveOutDate || null }); };
const updateTenant = async (id, data, user) => { const record = await getScopedRecord(Tenant, id, user); if (data.propertyId && String(data.propertyId) !== String(record.property)) await assertPortfolioAccess(data.propertyId, user); ["fullName", "email", "phone", "unit", "status", "moveInDate", "moveOutDate"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key] || null; }); if (data.tenantUserId !== undefined) record.tenantUser = data.tenantUserId || null; if (data.propertyId) record.property = data.propertyId; return record.save(); };

const createLease = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); const tenant = await getScopedRecord(Tenant, data.tenantId, user); if (String(tenant.property) !== String(data.propertyId)) throw new AppError("Tenant does not belong to the selected property", 400); const lease = await Lease.create({ property: data.propertyId, tenant: tenant._id, unit: data.unit || tenant.unit, startDate: data.startDate, endDate: data.endDate, monthlyRent: data.monthlyRent, deposit: data.deposit }); tenant.lease = lease._id; await tenant.save(); return lease; };
const updateLease = async (id, data, user) => { const record = await getScopedRecord(Lease, id, user); if (!["Active", "Expiring Soon"].includes(record.status)) throw new AppError("Only active leases can be updated", 400); ["unit", "endDate", "monthlyRent", "deposit"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key]; }); if (record.endDate <= record.startDate) throw new AppError("Lease end date must be after start date", 400); return record.save(); };
const renewLease = async (id, data, user) => { const record = await getScopedRecord(Lease, id, user); if (!["Active", "Expiring Soon", "Expired"].includes(record.status)) throw new AppError("This lease cannot be renewed", 400); if (new Date(data.startDate) < new Date(record.endDate)) throw new AppError("Renewal cannot begin before the current lease ends", 400); const renewed = await Lease.create({ property: record.property, tenant: record.tenant, unit: record.unit, startDate: data.startDate, endDate: data.endDate, monthlyRent: data.monthlyRent === undefined ? record.monthlyRent : data.monthlyRent, deposit: data.deposit === undefined ? record.deposit : data.deposit, status: "Active" }); record.status = "Renewed"; await record.save(); await Tenant.findByIdAndUpdate(record.tenant, { lease: renewed._id, status: "Active", moveOutDate: null }); return renewed; };
const terminateLease = async (id, reason, user) => { const record = await getScopedRecord(Lease, id, user); if (!["Active", "Expiring Soon"].includes(record.status)) throw new AppError("Only active leases can be terminated", 400); record.status = "Terminated"; record.terminationReason = reason; record.terminatedAt = new Date(); await record.save(); await Tenant.findByIdAndUpdate(record.tenant, { status: "Past", moveOutDate: new Date() }); return record; };

const createWorkOrder = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); if (data.tenantId) { const tenant = await getScopedRecord(Tenant, data.tenantId, user); if (String(tenant.property) !== String(data.propertyId)) throw new AppError("Tenant does not belong to the selected property", 400); } return WorkOrder.create({ property: data.propertyId, tenant: data.tenantId || null, unit: data.unit || null, title: data.title, description: data.description || "", priority: data.priority, estimatedCost: data.estimatedCost, actualCost: data.actualCost }); };
const updateWorkOrder = async (id, data, user) => { const record = await getScopedRecord(WorkOrder, id, user); if (["Resolved", "Closed", "Cancelled"].includes(record.status)) throw new AppError("Closed work orders cannot be edited", 400); ["unit", "title", "description", "priority", "estimatedCost", "actualCost"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key]; }); if (data.tenantId !== undefined) { if (data.tenantId) { const tenant = await getScopedRecord(Tenant, data.tenantId, user); if (String(tenant.property) !== String(record.property)) throw new AppError("Tenant does not belong to this work order's property", 400); } record.tenant = data.tenantId || null; } return record.save(); };
const assignWorkOrder = async (id, data, user) => { const record = await getScopedRecord(WorkOrder, id, user); if (!["Open", "Assigned"].includes(record.status)) throw new AppError("Only open work orders can be assigned", 400); if (data.vendorId) { const vendor = await Procurement.findOne({ _id: data.vendorId, recordType: "vendor" }).select("_id"); if (!vendor) throw new AppError("Vendor not found", 404); record.vendor = vendor._id; } if (data.assignedUserId !== undefined) record.assignedUser = data.assignedUserId || null; record.status = "Assigned"; return record.save(); };
const transitionWorkOrder = async (id, status, user) => { const record = await getScopedRecord(WorkOrder, id, user); const transitions = { Open: ["Assigned", "Cancelled"], Assigned: ["In Progress", "Open", "Cancelled"], "In Progress": ["Resolved", "Cancelled"], Resolved: ["Closed", "In Progress"], Closed: [], Cancelled: [] }; if (!transitions[record.status].includes(status)) throw new AppError("Invalid work order status transition", 400); record.status = status; if (status === "Resolved") record.resolvedAt = new Date(); if (status === "Closed") record.closedAt = new Date(); if (status === "Cancelled") record.cancelledAt = new Date(); return record.save(); };
const bulkAssignWorkOrders = async (ids, data, user) => { const records = await Promise.all(ids.map((id) => getScopedRecord(WorkOrder, id, user))); if (records.some((record) => !["Open", "Assigned"].includes(record.status))) throw new AppError("All work orders must be open or assigned", 400); return Promise.all(records.map((record) => assignWorkOrder(record._id, data, user))); };

const createInspection = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); if (data.tenantId) { const tenant = await getScopedRecord(Tenant, data.tenantId, user); if (String(tenant.property) !== String(data.propertyId)) throw new AppError("Tenant does not belong to the selected property", 400); } return Inspection.create({ property: data.propertyId, tenant: data.tenantId || null, unit: data.unit || null, scheduledAt: data.scheduledAt, inspector: data.inspectorId || null, inspectorName: data.inspectorName || null, type: data.type }); };
const updateInspection = async (id, data, user) => { const record = await getScopedRecord(Inspection, id, user); if (record.status !== "Scheduled") throw new AppError("Only scheduled inspections can be updated", 400); ["scheduledAt", "inspectorName", "type"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key]; }); if (data.inspectorId !== undefined) record.inspector = data.inspectorId || null; if (data.status === "Cancelled") record.status = "Cancelled"; return record.save(); };
const completeInspection = async (id, data, user) => { const record = await getScopedRecord(Inspection, id, user); if (!["Scheduled", "Pending Review"].includes(record.status)) throw new AppError("Only scheduled inspections can be completed", 400); record.status = "Completed"; record.score = data.score; record.findings = data.findings || []; record.reportUrl = data.reportUrl || null; record.completedAt = new Date(); await record.save(); await Property.findByIdAndUpdate(record.property, { inspectionStatus: "Completed", inspectionCompletedAt: record.completedAt, inspectedBy: record.inspector || user._id }); return record; };

const getPortfolioPayments = (user, query) => listRecords(Payment, user, query, ["tenant", "property"]);
const getPortfolioPayment = (id, user) => getScopedRecord(Payment, id, user, ["tenant", "property"]);
const updatePortfolioPaymentStatus = async (id, status, user) => { const record = await getScopedRecord(Payment, id, user); const transitions = { Pending: ["Paid", "Overdue", "Failed"], Overdue: ["Paid", "Failed"], Failed: ["Pending"], Paid: [] }; if (!transitions[record.status].includes(status)) throw new AppError("Invalid payment status transition", 400); record.status = status; record.paidAt = status === "Paid" ? new Date() : null; return record.save(); };

const createExpense = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); return Expense.create({ property: data.propertyId, category: data.category, amount: data.amount, expenseDate: data.expenseDate, description: data.description || "", vendorName: data.vendorName || null, receiptUrl: data.receiptUrl || null, createdBy: user._id }); };
const updateExpense = async (id, data, user) => { const record = await getScopedRecord(Expense, id, user); if (record.status !== "Pending") throw new AppError("Only pending expenses can be updated", 400); if (data.propertyId && String(data.propertyId) !== String(record.property)) await assertPortfolioAccess(data.propertyId, user); ["category", "amount", "expenseDate", "description", "vendorName", "receiptUrl"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key] || null; }); if (data.propertyId) record.property = data.propertyId; return record.save(); };
const approveExpense = async (id, user) => { if (!["Admin", "Super Admin"].includes(user.role)) throw new AppError("Only Admin and Super Admin can approve expenses", 403); const record = await getScopedRecord(Expense, id, user); if (record.status !== "Pending") throw new AppError("Only pending expenses can be approved", 400); record.status = "Approved"; record.approvedBy = user._id; record.approvedAt = new Date(); return record.save(); };
const createIncome = async (data, user) => { await assertPortfolioAccess(data.propertyId, user); return Income.create({ property: data.propertyId, category: data.category, amount: data.amount, incomeDate: data.incomeDate, description: data.description || "", createdBy: user._id }); };
const updateIncome = async (id, data, user) => { const record = await getScopedRecord(Income, id, user); if (data.propertyId && String(data.propertyId) !== String(record.property)) await assertPortfolioAccess(data.propertyId, user); ["category", "amount", "incomeDate", "description"].forEach((key) => { if (data[key] !== undefined) record[key] = data[key] || ""; }); if (data.propertyId) record.property = data.propertyId; return record.save(); };

const getSummary = async (user) => { const ids = await portfolioPropertyIds(user); const month = new Date(new Date().getFullYear(), new Date().getMonth(), 1); const [activeTenants, pendingRentPayments, openWorkOrders, activeLeases, pendingInspections, pendingExpenses, income] = await Promise.all([Tenant.countDocuments({ property: { $in: ids }, status: "Active" }), Payment.countDocuments({ property: { $in: ids }, status: { $in: ["Pending", "Overdue"] } }), WorkOrder.countDocuments({ property: { $in: ids }, status: { $in: ["Open", "Assigned", "In Progress"] } }), Lease.countDocuments({ property: { $in: ids }, status: { $in: ["Active", "Expiring Soon"] } }), Inspection.countDocuments({ property: { $in: ids }, status: { $in: ["Scheduled", "Pending Review"] } }), Expense.countDocuments({ property: { $in: ids }, status: "Pending" }), Income.aggregate([{ $match: { property: { $in: ids }, incomeDate: { $gte: month } } }, { $group: { _id: null, total: { $sum: "$amount" } } }])]); return { properties: ids.length, activeTenants, pendingRentPayments, openWorkOrders, activeLeases, pendingInspections, pendingExpenses, nonRentIncomeMonthToDate: income[0]?.total || 0 }; };
const getAnalytics = async (user) => { const ids = await portfolioPropertyIds(user); const [activeTenants, totalTenants, paid, overdue, expenses, income] = await Promise.all([Tenant.countDocuments({ property: { $in: ids }, status: "Active" }), Tenant.countDocuments({ property: { $in: ids } }), Payment.aggregate([{ $match: { property: { $in: ids }, status: "Paid" } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Payment.aggregate([{ $match: { property: { $in: ids }, status: "Overdue" } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Expense.aggregate([{ $match: { property: { $in: ids }, status: "Approved" } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Income.aggregate([{ $match: { property: { $in: ids } } }, { $group: { _id: null, total: { $sum: "$amount" } } }])]); const rentCollected = paid[0]?.total || 0; const approvedExpenses = expenses[0]?.total || 0; const nonRentIncome = income[0]?.total || 0; return { sufficientData: ids.length > 0, propertyCount: ids.length, activeOccupancies: activeTenants, totalOccupancyRecords: totalTenants, rentCollected, overdueRent: overdue[0]?.total || 0, approvedExpenses, nonRentIncome, netOperatingAmount: rentCollected + nonRentIncome - approvedExpenses }; };
const getDocuments = async (user) => { const ids = await portfolioPropertyIds(user); const [properties, leases, inspections] = await Promise.all([Property.find({ _id: { $in: ids }, "documents.0": { $exists: true } }).select("title documents"), Lease.find({ property: { $in: ids }, "documents.0": { $exists: true } }).select("property documents"), Inspection.find({ property: { $in: ids }, "documents.0": { $exists: true } }).select("property documents")]); return { propertyDocuments: properties.flatMap((record) => record.documents.map((document) => ({ ...document.toObject(), property: record._id, propertyTitle: record.title }))), leaseDocuments: leases.flatMap((record) => record.documents.map((document) => ({ ...document.toObject(), property: record.property, lease: record._id }))), inspectionDocuments: inspections.flatMap((record) => record.documents.map((document) => ({ ...document.toObject(), property: record.property, inspection: record._id }))) }; };

module.exports = { assertPortfolioAccess, getPortfolioProperties, listRecords, getScopedRecord, createTenant, updateTenant, createLease, updateLease, renewLease, terminateLease, createWorkOrder, updateWorkOrder, assignWorkOrder, transitionWorkOrder, bulkAssignWorkOrders, createInspection, updateInspection, completeInspection, getPortfolioPayments, getPortfolioPayment, updatePortfolioPaymentStatus, createExpense, updateExpense, approveExpense, createIncome, updateIncome, getSummary, getAnalytics, getDocuments };
